name: Print Each Status

on:
    workflow_dispatch:

jobs:
    cleanup-runs:
        runs-on: ubuntu-latest
        steps:
        - name: 実行中のワークフローのキャンセル
          uses: rokroskar/workflow-run-cleanup-action@master
          env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    build:
        runs-on: ubuntu-latest
        outputs:
            checkout_status: ${{ steps.checkout.outcome }}
            setup_jdk_status: ${{ steps.setup_jdk.outcome }}
            gradle_build_status: ${{ steps.gradle_build.outcome }}
        steps:
            - name: checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: setup jdk17
              id: setup_jdk
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'temurin'

            - name: gradle build
              id: gradle_build
              run: |
                ./gradlew build -i -s -x test --profile

    slack-workflow-status:
        runs-on: ubuntu-latest
        needs: [build]
        if: always()
        steps:
            - name: Slack Workflow Notification
              run: |
                echo "gradle_build_status:${{ needs.build.outputs.gradle_build_status }}"
